# YAML

# The spectrum sensing configurations.

my_radio1:
  spectrum_sensing:

    # Type must be ed (for energy detector) or wfd (for waveform detector). Anything different will raise an exception.
    type: ed

    # FFT size must be an integer.
    #fft_size: 1024

  # The USRP configurations.
  usrp:
    # The ip.
    ip: 10.1.1.146

  tx:

    type: gmsk
    # The parameter is not obrigatory. If you don't declare it, the default value will be used.
    #modulator: digital.gmsk_mod(samples_per_symbol=2, bt=0.35)
    samples_per_symbol: 2
    bt: 0.35

  rx:
    type: gmsk
    samples_per_symbol: 2    

my_radio2:
  spectrum_sensing:

    # Type must be ed (for energy detector) or wfd (for waveform detector). Anything different will raise an exception.
    type: ed
        
    # FFT size must be an integer.
    fft_size: 1024

  # The USRP configurations.
  usrp:
    # The ip.
    ip: 10.1.1.146

  tx:

    type: ofdm
    #modulation: "qam64"

  rx:
    type: ofdm
