python single_ss.py --sensing ed --ph1 0.1
python single_ss.py --sensing ed --ph1 0.5
python single_ss.py --sensing ed --ph1 0.9
python single_ss.py --sensing wfd --ph1 0.1
python single_ss.py --sensing wfd --ph1 0.5
python single_ss.py --sensing wfd --ph1 0.9
python single_ss.py --sensing cfd --ph1 0.1
python single_ss.py --sensing cfd --ph1 0.5
python single_ss.py --sensing cfd --ph1 0.9
python tsha.py --sensing cfd --ph1 0.1
python tsha.py --sensing cfd --ph1 0.5
python tsha.py --sensing cfd --ph1 0.9
python ata.py --sensing wfd --ph1 0.1
python ata.py --sensing wfd --ph1 0.5
python ata.py --sensing wfd --ph1 0.9
#python ata.py --sensing cfd --ph1 0.1
#python ata.py --sensing cfd --ph1 0.5
#python ata.py --sensing cfd --ph1 0.9
